name: Deployment

on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    permissions: write-all
    name: linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Update Libs
        run: sudo apt-get update  && sudo apt-get install -y libclang-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev && sudo apt-get install libudev-dev && cargo install cargo-bundle
      - name: Build
        run: cargo bundle --release
      #    - name: Compress.
      #      run: ls target/release/bundle/deb && cd target/release/bundle/deb && zip rust-serial-monitor.deb.zip *.deb
      - name: Rename
        run: ls target/release/bundle/deb && cd target/release/bundle/deb && mv *.deb rust-serial-monitor.deb
      - name: Upload Deb
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/release/bundle/deb/rust-serial-monitor.deb
          asset_name: rust-serial-monitor-linux_x86.deb
          asset_content_type: binary

  build-macos-x86:
    permissions: write-all
    name: macos x86
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Update Libs
        run: cargo install cargo-bundle
      - name: Build
        run: cargo bundle --release
      - name: Compress
        run: cd target/release/bundle/osx && ls && zip -r rust-serial-monitor.app.zip Serial\ Monitor.app/*
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/release/bundle/osx/rust-serial-monitor.app.zip
          asset_name: rust-serial-monitor-macos_x86.app.zip
          asset_content_type: binary

  build-macos-arm:
    permissions: write-all
    name: macos arm
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Update Libs
        run: cargo install cargo-bundle
      - name: Build
        run: cargo bundle --release
      - name: Compress
        run: cd target/release/bundle/osx && ls && zip -r rust-serial-monitor.app.zip Serial\ Monitor.app/*
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/release/bundle/osx/rust-serial-monitor.app.zip
          asset_name: rust-serial-monitor-macos_arm.app.zip
          asset_content_type: binary

  build-windows:
    permissions: write-all
    name: windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Update Libs
        run: cargo install cargo-wix
      - name: Build
        run: cargo wix
      - name: Compress
        run: cd target/wix && ls && Compress-Archive *.msi rust-serial-monitor.msi.zip
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/wix/rust-serial-monitor.msi.zip
          asset_name: rust-serial-monitor-windows_x86.msi.zip
          asset_content_type: binary
